In [2]:
import numpy as np

In [29]:
# Splitting of 1D array
a=np.array([1,2,3,4,5,6])
print(a)
x,y=np.split(a,2)
print(x,y)
x1,x2,x3=np.split(a,[2,4])
print(x1,x2,x3)
# Note: when the no of elements in the array is odd the split will
# raise an error.


[1 2 3 4 5 6]
[1 2 3] [4 5 6]
[1 2] [3 4] [5 6]


In [19]:
# Splitting of 2D array
a=np.array([[1,2,3],[4,5,6]])
print(a)
print("--------------")
x,y=np.split(a,2) # Here axis=0 is by default
print(x,y)
print("--------------")
x1,x2,x3=np.split(a,3,axis=1)
print(x1)
print("-------------")
print(x2)
print("-------------")
print(x3)


[[1 2 3]
 [4 5 6]]
--------------
[[1 2 3]] [[4 5 6]]
--------------
[[1]
 [4]]
-------------
[[2]
 [5]]
-------------
[[3]
 [6]]


In [30]:
# Splitting of 3D array
arr=np.array([[[1,2,3],
               [4,5,6]],

               [[7,8,9],
                [10,11,12]]
                ])
# print(arr) # Shape (2,2,3)
x1,x2,x3=np.dsplit(arr,3)
print(x1)
print(x2)
print(x3)
# Note: Here if we observe in the output the dimension and the shape remains the same but in the shape the no of blocks, no of rows are same

[[[ 1]
  [ 4]]

 [[ 7]
  [10]]]
[[[ 2]
  [ 5]]

 [[ 8]
  [11]]]
[[[ 3]
  [ 6]]

 [[ 9]
  [12]]]


In [38]:
# Applying vsplit and hsplit
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
a,b=np.vsplit(arr,2) # same as np.split(arr,2,axis=0) cuts horizontally (row wise)
print(a)
print("------")
print(b)
c,d,e=np.hsplit(arr,3) # same as np.split(arr,3,axis=1) cuts vertically (column wise)
print(c)
print("------")
print(d)
print("------")
print(e)


[[1 2 3]
 [4 5 6]]
[[1 2 3]]
------
[[4 5 6]]
[[1]
 [4]]
------
[[2]
 [5]]
------
[[3]
 [6]]


In [10]:
a="Rajiv Gandhi University of Knowledge and Technologies"
print(np.char.split(a))
# Here the words are splitted at whiltespaces and turned into a list of words
b="Apple-Banana-Orange-Carrot"
print(np.char.split(b,"-"))

['Rajiv', 'Gandhi', 'University', 'of', 'Knowledge', 'and', 'Technologies']
['Apple', 'Banana', 'Orange', 'Carrot']


In [ ]:
# Flatten: This numpy function makes any array to 1D but return a copy.

arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
b=arr.flatten()
print(arr.flatten()) #By default arr.flatten(order='C'), in this example we got 1D array row wise 
print(arr.flatten(order='F'))
# In this example we get 1D array column wise 
b[0]=100
print(b)
print(arr)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
[1 5 2 6 3 7 4 8]
[100   2   3   4   5   6   7   8]
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# Ravel: This numpy function makes any array to 1D but return a view.
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
b=arr.ravel()
print(arr.ravel()) #By default arr.ravel(order='C'), in this example we got 1D array row wise 
print(arr.ravel(order='F'))
# In this example we get 1D array column wise 
b[0]=100 # When we changed the b array value the original value is also changed.
print(b)
print(arr)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
[1 5 2 6 3 7 4 8]
[100   2   3   4   5   6   7   8]
[[100   2   3   4]
 [  5   6   7   8]]


In [24]:
arr=np.arange(0,16).reshape(4,4)
print(arr)
print(arr < 4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [False False False False]
 [False False False False]
 [False False False False]]


In [8]:
a=np.ones((3,1))
b=np.arange(3)
print(a,a.shape)
print(b, b.shape)
a+b

[[1.]
 [1.]
 [1.]] (3, 1)
[0 1 2] (3,)


array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])