#### Import the numpy package under the name np

In [2]:
import numpy as np

#### Print the numpy version and the configuration

In [2]:
print(np.__version__)
print(np.show_config)

2.3.1
<function show_config at 0x000001390AC7B240>


#### Create a null vector of size 10
##### Null vector: A null vector of size 10 is a vector that has 10 elements, and every element is 0

In [5]:
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### How to find the memory size of any array
##### **nbytes:** It is used to find the memory size of the array
##### **itemsize:** It is used to find the memory taken by a single element in the array.
##### **size:** It is used to find the no of elements in an array

In [11]:
arr=np.array([0,1,2,3,4,5])
print(arr.nbytes)
print(arr.itemsize)
print(arr.size)

48
8
6


##### How to get the documentation of the numpy add function from the command line?
We will get the documention of any function in using **help** keyword

In [ ]:
print(help(np.add))
print(np.add.__doc__)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

##### Create a null vector of size 10 but the fifth value which is 1

In [17]:
arr=np.zeros(10)
print(arr)
arr[4]=1
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


##### create a vector with values ranging from 10 to 49

In [18]:
arr=np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


##### Reverse a vector (first element becomes last)


In [27]:
arr=np.array([1,2,3,4,5,6])
print(arr[::-1])

[6 5 4 3 2 1]


##### Create a 3x3 matrix with values ranging from 0 to 8

In [31]:
arr=np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


##### Find indices of non-zero elements from [1,2,0,0,4,0]

In [33]:
arr=np.array([1,2,0,0,4,0])
indices=np.nonzero(arr)
print(indices[0])

[0 1 4]


#### Create a 3x3 identity matrix

In [36]:
arr=np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### Create a 3x3x3 array with random values

In [42]:
arr=np.random.random((3,3,3))
arr1=np.random.randint(0,27,(3,3,3))
print(arr)
print(arr1)

[[[0.00402988 0.80500822 0.81550101]
  [0.41834075 0.64747137 0.65199403]
  [0.73376217 0.06329856 0.88416875]]

 [[0.72318651 0.34187602 0.31158663]
  [0.85716598 0.334556   0.67068902]
  [0.19633101 0.95092191 0.63836175]]

 [[0.65931315 0.86655276 0.26547344]
  [0.15950332 0.15183998 0.08055905]
  [0.80439496 0.52392905 0.96389929]]]
[[[26 11 26]
  [25  5 22]
  [19 21  3]]

 [[12 18 15]
  [11 18  0]
  [ 3  5 14]]

 [[19  8 16]
  [ 3  9  2]
  [13 23  8]]]


##### Create a 10x10 array with random values and find the minimum and maximum values

In [44]:
arr=np.random.randint(0,27,(10,10))
print(arr)
print("The maximum value",arr.max())
print("The minimum value",arr.min())

[[ 8 12 17 20 20 18  2  4 19 13]
 [24 15 16 22 14 24 17 25  4 26]
 [11 26  7 16  5 12  3  1  5  6]
 [ 6  0 23  3 23 22  3 25  2  7]
 [17 26 25  7  0  1 24  7  8 26]
 [19 19  9 24 25 16 26  1 22  5]
 [ 5 14 23  4  3 22 10  3 22 25]
 [13  4 17  7 11 15 26 11  9  0]
 [14 21 15 17  8  3 23 24 10  3]
 [26 24  6 22  2 20 13 11 19 24]]
The maximum value 26
The minimum value 0


##### Create a random vector of size 30 and find the mean value
 <p style="font-family:Monospace">
 As it is a random vector we cannot expect the same output every time.
 But if we use np.random.seed(42) then the mean value is same for every time we run.
 </p>

In [56]:
np.random.seed(42)
arr=np.random.randint(0,30,size=30)
print(arr)
print("The mean value is",arr.mean())

[ 6 19 28 14 10  7 28 20  6 25 18 22 10 10 23 20  3  7 23  2 21 20  1 23
 11 29  5  1 27 20]
The mean value is 15.3


##### Create a 2d array with 1 on the border and 0 inside

In [65]:
arr=np.ones((3,3),dtype=int)
arr[1][1]=0
print(arr)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


##### How to add a border (filled with 0's) around an exisiting array?


<p>Method 1</p>

In [15]:
arr=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10],
              [11,12,13,14],[15,16,17,18]])
print(arr) # this is the original array
arr[0,:]=0
arr[-1,:]=0
arr[:,0]=0
arr[:,-1]=0
print(arr) # this is the array after modification

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]
 [11 12 13 14]
 [15 16 17 18]]
[[ 0  0  0  0]
 [ 0  5  6  0]
 [ 0  8  9  0]
 [ 0 12 13  0]
 [ 0  0  0  0]]


<p>Method 2</p>

In [17]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

result=np.pad(arr,pad_width=1,mode="constant",constant_values=0)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


##### Create a 3x3 diagonal matrix with values [2,4,6]

In [3]:
arr=np.diag([2,4,6])
print(arr)

[[2 0 0]
 [0 4 0]
 [0 0 6]]


##### Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [7]:
arr=np.zeros((5,5),dtype=int)
arr1=np.diag([1,2,3,4],k=-1)
print(arr1)
arr[1:,:-1] +=np.diag([1,2,3,4])
print(arr)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [18]:
arr=np.arange(25).reshape(5,5)
print(arr)

# print(arr[:,::2])
print(arr[::-1,:])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[20 21 22 23 24]
 [15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]


##### Create a 8x8 matrix and fill it with a checkerboard pattern 


In [27]:
arr=np.ones((8,8))
arr[::2,::2]=0
arr[1::2,1::2]=0
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


##### Consider a (6,7,8) shape array, what is index (x,y,z) of the 100th element

In [30]:
arr=np.random.random((6,7,8))
# print(arr)
print(arr.size)
# print(arr)

336


In [43]:
arr=np.random.random((6,7,8))
# print(arr)
index=np.unravel_index(99,arr.shape)
print(index)

(np.int64(1), np.int64(5), np.int64(3))


In [1]:
import numpy as np

# Direct link to the dataset
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv'

# Load the data (skipping the first row which contains text headers, and splitting by semicolon)
wine_data = np.genfromtxt(url, delimiter=';', skip_header=1)

print("Shape of the dataset:", wine_data.shape) 
# Output will be (1599, 12) - meaning 1599 rows (wines) and 12 columns (features)

Shape of the dataset: (1599, 12)


In [2]:
print(wine_data)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]
